/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package simple.medical.record;

import java.util.Scanner;

// import javax.crypto.spec.PBEKeySpec;

import simple.medical.record.services.LoginService;
import simple.medical.record.services.RegisterService;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Runner runner = new Runner();
        runner.run();
        String[] serviceNames = { "register", "login" };

        System.out.println("Welcome to simple medical record system!");
        System.out.println("Main menu:");
        Scanner sc = new Scanner(System.in);

        for (int i = 0; i < serviceNames.length; i++) {
            String serviceName = serviceNames[i];
            System.out.println(i + 1 + "." + "" + serviceName);
        }

        System.out.print("=> Choice: ");
        int selected = sc.nextInt();
        switch (selected) {
            case 1:
                System.out.println("Register selected!");
                RegisterService.run();
                break;
            case 2:
                System.out.println("Login selected!");
                LoginService.run();
                break;
            default:
                System.out.println("Invalid service to select");
                break;
        }
        sc.close();
    }
}
