/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package simple.medical.record;

import java.sql.Date;

import simple.medical.record.domains.Address;
import simple.medical.record.domains.Person;
import simple.medical.record.repository.PersonRepo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Runner runner = new Runner();
        runner.run();
        PersonRepo personRepo = new PersonRepo("person");
        Date date = new Date(2003, 5, 12);
        Person person1 = new Person("first", "last", "M", date, new String[] { "123233" },
                new Address("b", "c", "c", "c"),
                "1234");
        personRepo.create(person1);
        System.out.println(new App().getGreeting());
    }
}
